export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Partners } from './Partners'
export { default as Register } from './Register'
export { default as Solution } from './Solution'
export { default as Blogs } from './Blogs'
export { default as Navbar } from './Navbar'